// ref js/reveal.js

import plugAnimate from 'plugin/animate/plugin.js'
import plugAnything from 'plugin/anything/plugin.js'
import plugAutoSlideshow from 'plugin/audio-slideshow/plugin.js'
import plugAutoSlideshowRec from 'plugin/audio-slideshow/recorder.js'
import plugAutoSlideshowRtc from 'plugin/audio-slideshow/RecordRTC.js'
import plugChalkboard from 'plugin/chalkboard/plugin.js'
import plugChart from 'plugin/chart/plugin.js'
import plugChart from 'plugin/chart/Chart.js'
import plugChart from 'plugin/chart/Chart.min.js'
import plugCustomControls from 'plugin/customcontrols/plugin.js'
import plugEmbedTweet from 'plugin/embed-tweet/plugin.js'
import plugFullscreen from ''
import plugMath from ''
import plugMath from ''
import plugMath from ''
import plugSearch from ''
import plugSearch from ''
import plugSearch from ''
import plugZoom from ''
import plugZoom from ''
import plugZoom from ''
